# ==============================================
# Created By: Hossam Mahmoud
# Date: 2025-02-04
# Filename: Dockerfile
# Description: Dockerfile to run a CentOs image to use Ansible on
# Version: 1.0.0
# Last Modified: 2025-02-04 by Hossam
# Copyright (c) 2025 Hossam. All rights reserved.
# TODO: Add future tasks or improvements
# ==============================================

# Use version 7 of centos
FROM centos:7

# Update YUM repository configuration to use vault.centos.org
RUN cd /etc/yum.repos.d/ && \
        sed -i 's/mirrorlist/#mirrorlist/g' CentOS-* && \
        sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' CentOS-* && \
        yum clean all && \
        yum update -y

# Install SSH and sudo
RUN yum install -y openssh-server sudo

# Add user 'hosa-iti' and set password
RUN useradd hosa-iti && \
        echo "hosa-iti:123" | chpasswd && \
        usermod -aG wheel hosa-iti

# # Enable SSH service
# RUN service ssh start

# Start SSH service when the container runs
CMD ["/usr/sbin/sshd", "-D"]
