---
- name: Deploy Nginx and other configs
  hosts: all
  become: yes  # Run tasks with sudo privileges
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install the latest version of Nginx
      apt:
        name: nginx
        state: latest

    - name: Copy index.html from controller to host
      copy:
        src: ./index.html      # Replace with the actual path on the controller
        dest: /var/www/html/index.html
        owner: www-data
        group: www-data
        mode: '0644'

    - name: Restart Nginx service
      service:
        name: nginx
        state: restarted
        use: service
