---
- name: Simple playbook to implement VARIABLES
  hosts: all
  become: yes  # Run tasks with sudo privileges
  gather_facts: yes # Ensures Ansible collect env facts
  # vars:
  #   package_name: curl
  #   package_version: latest
  
  tasks: # Here i will specify the tasks that I want to create
    - name: Install {{package_name}} version {{package_version}}
      tags: install
      apt:
        name: "{{ package_name }}"
        state: "{{ package_version }}"
        update_cache: yes

    # - name: Install {{package_name}} version {{package_version}}
    #   tags: install
    #   apt:
    #     name: "{{ package_name }}"
    #     state: "{{ package_version }}"
    #     update_cache: yes

    # - name: Install the latest version of Nginx
    #   tags: install
    #   apt:
    #     name: nginx
    #     state: latest
    
    - name: Display the current user name
      tags: always
      debug:
        msg: "The current user is {{ ansible_env.USER }}"
