---
- name: Simple playbook to implement TAGS
  hosts: all
  become: yes  # Run tasks with sudo privileges
  tasks: # Here i will specify the tasks that I want to create

    - name: Update apt cache
      tags: update
      apt:
        update_cache: yes

    - name: Install the latest version of Nginx
      tags: install
      apt:
        name: nginx
        state: latest