---
- name: Simple playbook to implement TAGS
  hosts: all
  become: yes  # Run tasks with sudo privileges
  gather_facts: yes # Ensures Ansible collect env facts
  tasks: # Here i will specify the tasks that I want to create

    - name: Update apt cache
      tags: update
      apt:
        update_cache: yes

    - name: Install the latest version of Nginx
      tags: install
      apt:
        name: nginx
        state: latest
    
    - name: Display the current user name
      tags: always
      debug:
        msg: "The current user is {{ ansible_env.USER }}"
