---
- name: Simple playbook to implement WHEN
  hosts: all
  become: yes  # Run tasks with sudo privileges
  gather_facts: yes # Ensures Ansible collect env facts
  
  tasks: # Here i will specify the tasks that I want to create
    - name: Install nginx based on distribution
      tags: install
      apt:
        name: nginx
        state: latest
        update_cache: yes
      when: ansible_facts['distribution'] == "Ubuntu"
  
    - name: Install apache based on condition
      tags: install
      apt:
        name: httpd
        state: latest
        update_cache: yes
      when: ansible_facts['distribution'] == "CentOs"

    - name: Display the current user name
      tags: always
      debug:
        msg: "The current user is {{ ansible_env.USER }}"

    # - name: Install {{package_name}} version {{package_version}}
    #   tags: install
    #   apt:
    #     name: "{{ package_name }}"
    #     state: "{{ package_version }}"
    #     update_cache: yes

    # - name: Install the latest version of Nginx
    #   tags: install
    #   apt:
    #     name: nginx
    #     state: latest
