# ==============================================
# Created By: Hossam Mahmoud
# Date: 2025-01-19
# Filename: Dockerfile
# Description: Multistage Dockerfile to run the React app
# Version: 1.0.0
# Last Modified: 2025-01-19 by Hossam
# Copyright (c) 2025 Hossam. All rights reserved.
# TODO: Add future tasks or improvements
# ==============================================

# Use the latest LTS version of Node.js
FROM ubuntu:22.04

# Sets the entrypoint to sleep
ENTRYPOINT [ "sleep" ]
 
# Sets the time of the sleeper
CMD ["15"]